name: Build Ezra Project packages

on:
  push:
  release:
    types:
      - published

jobs:
    build-win32:
        name: Build Windows installer
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - name: Install Windows build tools
          run: powershell npm install windows-build-tools --vs2015
        - name: Install electron-installer-windows
          run: powershell npm install electron-installer-windows
        - name: Build
          run: powershell .\build_scripts\build_win32.bat
        - name: Rename installer
          run: Get-ChildItem release\packages\*setup.exe | rename-item -NewName { "ezra-project_win32_setup_latest.exe" }
          shell: pwsh
        - name: Upload installer
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_win32_latest
            path: release\packages\ezra-project_win32_setup_latest.exe

    build-mac:
        name: Build macOS DMG file
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v1
        - name: Install pkg-config
          run: brew install pkg-config
        - name: Build
          run: npm run build-mac
        - name: Generate dmg
          run: npm install electron-installer-dmg macos-alias ds-store && npm run dmg-mac
        - name: Upload dmg
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_macos_latest
            path: release/ezra-project.dmg

    build-ubuntu-1804:
        name: Build Ubuntu 18.04 package
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build
          uses: ./.github/actions/build_ubuntu1804
        - name: Upload deb file
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_ubuntu1804_latest
            path: ezra-project_latest.deb

    build-ubuntu-1910:
        name: Build Ubuntu 19.10 package
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build
          uses: ./.github/actions/build_ubuntu1910
        - name: Upload deb file
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_ubuntu1910_latest
            path: ezra-project_latest.deb

    build-mint18:
        name: Build Mint 18 package
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build
          uses: ./.github/actions/build_mint18
        - name: Upload deb file
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_mint18_latest
            path: ezra-project_latest.deb

    build-mint19:
        name: Build Mint 19 package
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build
          uses: ./.github/actions/build_mint19
        - name: Upload deb file
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_mint19_latest
            path: ezra-project_latest.deb

    build-buster:
        name: Build Debian 10 package
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build
          uses: ./.github/actions/build_buster
        - name: Upload deb file
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_debian10_latest
            path: ezra-project_latest.deb

    build-fedora29:
        name: Build Fedora 29 package
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build
          uses: ./.github/actions/build_fedora29
        - name: Upload rpm file
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_fedora29_latest
            path: ezra-project_latest.rpm

    build-fedora31:
        name: Build Fedora 31 package
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build
          uses: ./.github/actions/build_fedora31
        - name: Upload rpm file
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_fedora31_latest
            path: ezra-project_latest.rpm

    build-centos8:
        name: Build CentOS 8 package
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build
          uses: ./.github/actions/build_centos8
        - name: Upload rpm file
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_centos8_latest
            path: ezra-project_latest.rpm

    build-opensuse-leap:
        name: Build OpenSuse Leap package
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Build
          uses: ./.github/actions/build_opensuseleap
        - name: Upload rpm file
          uses: actions/upload-artifact@master
          with:
            name: ezra-project_opensuse_leap_latest
            path: ezra-project_latest.rpm

    release:
      if: "github.event.release"
      name: Publish release artifacts
      runs-on: ubuntu-latest
      needs: [ build-win32, build-ubuntu-1804, build-ubuntu-1910, build-mint18, build-mint19, build-buster, build-fedora29, build-fedora31, build-centos8, build-opensuse-leap ]

      steps:
      - name: Download win32 package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_win32_latest

      - name: Download ubuntu-1804 package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_ubuntu1804_latest

      - name: Download ubuntu-1910 package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_ubuntu1910_latest

      - name: Download mint18 package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_mint18_latest

      - name: Download mint19 package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_mint19_latest

      - name: Download debian10 package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_debian10_latest

      - name: Download fedora29 package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_fedora29_latest

      - name: Download fedora31 package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_fedora31_latest

      - name: Download centos8 package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_centos8_latest

      - name: Download opensuse leap package
        uses: actions/download-artifact@master
        with:
          name: ezra-project_opensuse_leap_latest

      - name: Rename artifacts for publishing
        shell: bash
        run: |
          mkdir packages
          mv ezra-project_win32_latest/ezra-project_win32_setup_latest.exe packages/ezra-project_win32_setup-${GITHUB_REF##*/}.exe
          mv ezra-project_ubuntu1804_latest/ezra-project_latest.deb packages/ezra-project_ubuntu1804-${GITHUB_REF##*/}.deb
          mv ezra-project_ubuntu1910_latest/ezra-project_latest.deb packages/ezra-project_ubuntu1910-${GITHUB_REF##*/}.deb
          mv ezra-project_mint18_latest/ezra-project_latest.deb packages/ezra-project_mint18-${GITHUB_REF##*/}.deb
          mv ezra-project_mint19_latest/ezra-project_latest.deb packages/ezra-project_mint19-${GITHUB_REF##*/}.deb
          mv ezra-project_debian10_latest/ezra-project_latest.deb packages/ezra-project_debian10-${GITHUB_REF##*/}.deb
          mv ezra-project_fedora29_latest/ezra-project_latest.rpm packages/ezra-project_fedora29-${GITHUB_REF##*/}.rpm
          mv ezra-project_fedora31_latest/ezra-project_latest.rpm packages/ezra-project_fedora31-${GITHUB_REF##*/}.rpm
          mv ezra-project_centos8_latest/ezra-project_latest.rpm packages/ezra-project_centos8-${GITHUB_REF##*/}.rpm
          mv ezra-project_opensuse_leap_latest/ezra-project_latest.rpm packages/ezra-project_opensuse_leap-${GITHUB_REF##*/}.rpm

      - name: Publish artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'packages/*.*'

